openapi: 3.0.0
info:
  version: 1.0.0
  title: management API
  description: management API
paths:
  /login:
    post:
      description: ログイン
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/login_body'
      responses:
        200:
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'

        403:
          description: 失敗

components:
  schemas:
    login_body:
      type: object
      required:
        - login_id
        - password
      properties:
        login_id:
          description: ログインID
          type: string
          example: '1'
        password:
          description: パスワード
          required:
            - login_id
          type: string
    user:
      type: object
      properties:
        name:
          description: 名前
          type: string
          example: 'XXX'
